name: aegisub
version: "3.2.2"
summary: Aegisub is a free and open source tool for creating and modifying subtitles. 
description: Aegisub makes it quick and easy to time subtitles to audio, and features many powerful tools for styling them, including a built-in real-time video preview.
type: app
icon: packages/desktop/64x64.png
grade: stable
confinement: strict

apps:
  aegisub:
    command: desktop-launch $SNAP/bin/aegisub-3.2
    plugs: [alsa, home, desktop, opengl, wayland, x11, unity7]

parts:
  aegisub:
    source: https://github.com/reimashi/Aegisub/archive/3.2.tar.gz
    plugin: autotools
    install-via: prefix
    build-packages:
    - libboost-all-dev
    - intltool
    - libasound2-dev
    - libass-dev
    - libffms2-dev
    - libfftw3-dev
    - libgl1-mesa-dev
    - libglu1-mesa-dev
    - libgtk2.0-dev
    - libhunspell-dev
    - liblua5.1-dev
    - libwxgtk3.0-dev
    - libicu-dev
    stage-packages:
    - libasound2
    - libass5
    - libboost-filesystem1.65.0
    - libboost-locale1.65.0
    - libboost-regex1.65.0
    - libboost-system1.65.0
    - libboost-thread1.65.0
    - libc6
    - libffms2-4
    - libfftw3-double3
    - libfontconfig1
    - libgcc1
    - libgl1-mesa-glx
    - libhunspell-1.3-0
    - libicu55
    - libluajit-5.1-2
    - libpulse0
    - libstdc++6
    - libwxbase3.0-0v5
    - libwxgtk3.0-0v5
    - zlib1g
    after: [desktop-gtk3]
