name: aegisub
version: "3.2.2"
summary: Aegisub is a free and open source tool for creating and modifying subtitles. 
description: Aegisub makes it quick and easy to time subtitles to audio, and features many powerful tools for styling them, including a built-in real-time video preview.
type: app
icon: packages/desktop/64x64.png
grade: stable
confinement: strict

apps:
  aegisub:
    command: usr/local/bin/aegisub-3.2
    plugs: [alsa, home, desktop, opengl]

parts:
  aegisub:
    plugin: autotools
    source: https://github.com/reimashi/Aegisub/archive/3.2.tar.gz
    build-packages:
    - libboost-all-dev
    - intltool
    - libasound2-dev
    - libass-dev
    - libffms2-dev
    - libfftw3-dev
    - libgl1-mesa-dev
    - libglu1-mesa-dev
    - libgtk2.0-dev
    - libhunspell-dev
    - liblua5.1-dev
    - libwxgtk3.0-dev
    - libicu-dev
    stage-packages:
    - libstdc++6
